version: '3'

# For dev use only - hence ${PWD}
services:
  app:
    command: npm start
    build: .
    ports:
      - 3000:3000
    volumes:
      - ${PWD}/src:/workspace/src
      - node_modules:/workspace/node_modules
    environment:
      PORT: 3000

volumes:
  node_modules: {}
